services:
          - type: web
            name: django-app
            env: python
            buildCommand: pip install -r requirements.txt
            startCommand: gunicorn django_app.wsgi --log-file -
