# Exported from Render on 2025-10-05T01:44:54Z
version: "1"
services:
- type: web
  name: django-app
  runtime: python
  repo: https://github.com/engwilliamvieirafontenele/base_psique_arcane2
  branch: master
  plan: starter
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn base_psique_arcane2/core/wsgi.py
  autoDeployTrigger: commit
